### ISSUE TITLE
Did work stop? They are great icons 

### ISSUE THREAD

**Issue by IvanDeFelice76** [balasakthi88/OS-X-Impression#2]
Theme is very nice, but various icons should be reviewed or added, I hope work has not stopped 

ADD ICON: Cockpit,Alinkcreator,Amule,AmuleGui,Wxcas,Photo,Abrt,

and more will be added shortly

**Comment by balasakthi** [comment]
Thankyou very much for your response. Yes many of the icons have to be changed and to be added.
